const fs = require('fs');
const file = 'src/app/(main)/create-recipe/page.tsx';
let content = fs.readFileSync(file, 'utf8');
const startStr = 'id="form-field-setIngredients"';
const startIndex = content.lastIndexOf('<div', content.indexOf(startStr));
const endStr = 'เพิ่มวัตถุดิบในเซ็ทอาหาร';
const endIndex = content.indexOf('</div>', content.indexOf(endStr)) + 6;
const block = content.substring(startIndex, endIndex);
content = content.substring(0, startIndex) + content.substring(endIndex);
const targetIndex = content.indexOf('id="form-field-shopDescription"');
const insertIndex = content.indexOf('</div>', targetIndex) + 6;
content = content.substring(0, insertIndex) + '\n\n' + block + content.substring(insertIndex);
fs.writeFileSync(file, content);
console.log('Moved setIngredients');
