-- Generated by: prisma migrate diff --from-url <db> --to-schema-datamodel schema.prisma
-- Reconciles database schema with the current Prisma schema after historical drift:
--   - drops orphan columns "discount"/"role" mistakenly added to "ingredients" by migration 20260709081028
--   - adds missing "visibility" column on "recipes"
--   - creates tables missing from migration history: store_posts, store_post_images, store_post_videos, recipe_equipment

-- AlterTable
ALTER TABLE "ingredients" DROP COLUMN "discount",
DROP COLUMN "role";

-- AlterTable
ALTER TABLE "recipes" ADD COLUMN     "visibility" TEXT NOT NULL DEFAULT 'public';

-- CreateTable
CREATE TABLE "store_posts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "userId" UUID NOT NULL,
    "recipeId" UUID NOT NULL,
    "storeName" TEXT NOT NULL,
    "sellingPrice" DOUBLE PRECISION NOT NULL,
    "storeDescription" TEXT,
    "storeLocation" TEXT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "store_posts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "store_post_images" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "storePostId" UUID NOT NULL,
    "imageUrl" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "store_post_images_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "store_post_videos" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "storePostId" UUID NOT NULL,
    "videoUrl" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "store_post_videos_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "recipe_equipment" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "recipeId" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "recipe_equipment_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "store_posts" ADD CONSTRAINT "store_posts_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "store_posts" ADD CONSTRAINT "store_posts_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "recipes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "store_post_images" ADD CONSTRAINT "store_post_images_storePostId_fkey" FOREIGN KEY ("storePostId") REFERENCES "store_posts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "store_post_videos" ADD CONSTRAINT "store_post_videos_storePostId_fkey" FOREIGN KEY ("storePostId") REFERENCES "store_posts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "recipe_equipment" ADD CONSTRAINT "recipe_equipment_recipeId_fkey" FOREIGN KEY ("recipeId") REFERENCES "recipes"("id") ON DELETE CASCADE ON UPDATE CASCADE;
